"""Asynchronous local client for LinknLink eMotion devices."""

from .client import (
    DISPLAY_MODEL_EMOTION,
    DISPLAY_MODEL_ULTRA2,
    PID_EMOTION,
    PID_ULTRA2,
    TYPE_EMOTION,
    TYPE_ULTRA2,
    TYPE_ULTRA2_LAN,
    UltraAuthError,
    UltraClient,
    UltraConnectionError,
    UltraError,
    UltraProtocolError,
    derive_ultra2_protocol_mac,
    derive_ultra2_radar_did,
)
from .local_udp import UltraPositionSubscription
from .models import (
    EmotionPresenceState,
    UltraDevice,
    UltraEnvironmentState,
    UltraLocalUDPConfig,
    UltraPositionSubscriptionState,
    UltraPositionUpdate,
    UltraRadarStatus,
    UltraRadarZRange,
    UltraSession,
    UltraTargetPosition,
)

__all__ = [
    "DISPLAY_MODEL_EMOTION",
    "DISPLAY_MODEL_ULTRA2",
    "PID_EMOTION",
    "PID_ULTRA2",
    "TYPE_EMOTION",
    "TYPE_ULTRA2",
    "TYPE_ULTRA2_LAN",
    "UltraAuthError",
    "UltraClient",
    "UltraConnectionError",
    "UltraDevice",
    "UltraEnvironmentState",
    "EmotionPresenceState",
    "UltraError",
    "UltraLocalUDPConfig",
    "UltraPositionSubscription",
    "UltraPositionSubscriptionState",
    "UltraPositionUpdate",
    "UltraProtocolError",
    "UltraRadarStatus",
    "UltraRadarZRange",
    "UltraSession",
    "UltraTargetPosition",
    "derive_ultra2_radar_did",
    "derive_ultra2_protocol_mac",
]
